# Generated by Django 4.2.7 on 2023-12-21 17:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('care_name', models.CharField(max_length=100)),
                ('car_version', models.CharField(max_length=3)),
                ('car_model', models.CharField(max_length=30)),
            ],
        ),
    ]
